name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.YC_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.YC_SECRET_ACCESS_KEY }}
          aws configure set default.region ru-central1

      - name: Archive project
        run: |
          zip -r project.zip .

      - name: Upload project to Yandex Object Storage
        run: |
          aws --endpoint-url=https://storage.yandexcloud.net \
            s3 cp project.zip s3://qq-my-bucket/project.zip

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "export PATH=\$PATH:/home/runner/yandex-cloud/bin" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Set Yandex Cloud OAuth token
        run: |
          /home/runner/yandex-cloud/bin/yc config set token ${{ secrets.YC_OAUTH_TOKEN }}

      - name: Configure Yandex Cloud CLI
        run: |
          /home/runner/yandex-cloud/bin/yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          /home/runner/yandex-cloud/bin/yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Create VM and deploy project
        run: |
          echo "#cloud-config
          datasource:
            Ec2:
              strict_id: false
          ssh_pwauth: no
          users:
          - name: qqkazakov
            sudo: 'ALL=(ALL) NOPASSWD:ALL'
            shell: /bin/bash
            ssh_authorized_keys:
            - ${{ secrets.SSH_PRIVATE_KEY }}
          runcmd: []" > metadata.yaml

          /home/runner/yandex-cloud/bin/yc compute instance create \
            --name flask-app-vm \
            --zone ru-central1-a \
            --network-interface subnet-name=default-ru-central1-a,nat-ip-version=ipv4 \
            --create-boot-disk image-family=ubuntu-2004-lts,size=10GB \
            --metadata-from-file user-data=metadata.yaml
