name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.YC_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.YC_SECRET_ACCESS_KEY }}
          aws configure set default.region ru-central1

      - name: Archive project
        run: |
          zip -r project.zip .

      - name: Upload project to Yandex Object Storage
        run: |
          aws --endpoint-url=https://storage.yandexcloud.net \
            s3 cp project.zip s3://qq-my-bucket/project.zip

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          yc init --token=${{ secrets.YC_TOKEN }}

      - name: Configure Yandex Cloud CLI
        run: |
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Create VM and deploy project
        run: |
          yc compute instance create \
            --name flask-app-vm \
            --zone ru-central1-a \
            --network-interface subnet-name=default-ru-central1-a,nat-ip-version=ipv4 \
            --create-boot-disk image-family=ubuntu-2004-lts,size=10GB \
            --ssh-key ~/.ssh/id_rsa.pub

          yc compute instance add-metadata \
            --name flask-app-vm \
            --metadata-from-file user-data=deploy-script.sh

